name: Java Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        # 폴더 안으로 이동해서 빌드하도록 수정했습니다.
        run: |
          cd apocalypse_escape_fullpack
          if [ -f "./gradlew" ]; then
            chmod +x gradlew
            ./gradlew build
          else
            echo "Gradle wrapper still not found in subdirectory"
            exit 1
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: "**/build/libs/*.jar"
